# Flujo de trabajo de muestra para crear e implementar un sitio Jekyll en GitHub Pages
nombre : Implementar Jekyll con las dependencias de GitHub Pages preinstaladas

en :
  # Se ejecuta en envíos dirigidos a la rama predeterminada
  empujar :
    ramas : ["principal"]

  # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  flujo de trabajo_despacho :

# Establece los permisos de GITHUB_TOKEN para permitir la implementación en páginas de GitHub
permisos :
  Contenido : leer
  páginas : escribir
  id-token : escribir

# Permitir solo una implementación simultánea, omitiendo las ejecuciones en cola entre la ejecución en curso y la última en cola.
# Sin embargo, NO cancele las ejecuciones en curso ya que queremos permitir que estas implementaciones de producción se completen.
concurrencia :
  grupo : " páginas "
  cancelación en curso : falso

trabajos :
  # Construir trabajo
  construir :
    se ejecuta en : ubuntu-latest
    pasos :
      - nombre : Caja
        usos : acciones/checkout@v4
      - nombre : Páginas de configuración
        usos : acciones/configure-pages@v5
      - nombre : Construye con Jekyll
        usos : acciones/jekyll-build-pages@v1
        con :
          fuente : ./
          destino : ./_site
      - nombre : Subir artefacto
        usos : acciones/upload-pages-artifact@v3

  # Trabajo de implementación
  desplegar :
    ambiente :
      nombre : github-pages
      URL : ${{ pasos.implementación.salidas.página_url }}
    se ejecuta en : ubuntu-latest
    necesidades : construir
    pasos :
      - nombre : Implementar en páginas de GitHub
        id : implementación
        usos : acciones/páginas-de-implementación@v4
